### ISSUE TITLE
error in option 10 : get target info

### ISSUE THREAD

**Issue by lCyPh3r** [EchterAlsFake/Osintgram2#2]
T) Set Target
1) - addrs           Get all registered addressed by target photos
2) - captions        Get user's photos captions
3) - comments        Get total comments of target's posts
4) - followers       Get target followers
5) - followings      Get users followed by target
6) - fwersemail      Get email of target followers
7) - fwingsemail     Get email of users followed by target
8) - fwersnumber     Get phone number of target followers
9) - fwingsnumber    Get phone number of users followed by target
10) - info            Get target info
11) - likes           Get total likes of target's posts
12) - mediatype       Get user's posts type (photo or video)
13) - photos          Download user's photos in output folder
14) - propic          Download user's profile picture
15) - stories         Download user's stories
16) - Exit

-------------------=>:10
Traceback (most recent call last):
  File "C:\Users\bobme\Desktop\Tools\Osintgram2\Osintgram.py", line 509, in <module>
    Osintgram_like_datalux()
  File "C:\Users\bobme\Desktop\Tools\Osintgram2\Osintgram.py", line 84, in __init__
    self.menu()
  File "C:\Users\bobme\Desktop\Tools\Osintgram2\Osintgram.py", line 136, in menu
    self.get_info()
  File "C:\Users\bobme\Desktop\Tools\Osintgram2\Osintgram.py", line 418, in get_info
    print(f"""
  File "C:\Users\bobme\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1256.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f31d' in position 313: character maps to <undefined>

**Comment by EchterAlsFake** [comment]
Fixed with commit [bb9e65d (https://github.com/EchterAlsFake/Osintgram2/commit/bb9e65dca038cdf074a3dcb170a304ab1f6392f7)

Thanks for reporting :)
