### ISSUE TITLE
Issue with comments 

### ISSUE THREAD

**Issue by chydn0y** [EchterAlsFake/Osintgram2#6]
Enter between 1 - 100 (default: 50) -->:
50
Fetching media: 100%|█████████████████████████████████████████████████████████████████████████| 366/366 [00:34<00:00, 10.52it/s]
Traceback (most recent call last):
  File "Osintgram.py", line 862, in <module>
    execute()
  File "Osintgram.py", line 825, in execute
    Osintgram()
  File "Osintgram.py", line 133, in __init__
    self.menu()
  File "Osintgram.py", line 272, in menu
    getattr(self, method)()
  File "Osintgram.py", line 430, in get_comments
    with open(f"{self.target}{os.sep}comments{os.sep}comments.txt") as comments_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'username/comments/comments.txt'
[179970] Failed to execute script 'Osintgram' due to unhandled exception!

**Comment by EchterAlsFake** [comment]
Thanks for reporting, I'll fix that tomorrow :)

**Comment by Chydnoy** [comment]
Hello! I found few more bugs , i can post them if you want

**Comment by EchterAlsFake** [comment]
Yes please post them all, I'll fix them tomorrow :)

**Comment by EchterAlsFake** [comment]
Instagram blocks me out constantly. I can't test anything currently. I know about the errors and I try to fix them, but it's currently a mess.

If anyone of you get's the error with a file not being found you can just create that text file in the folder. A bit stupid for now, but I can't do so much now.
